# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1a369185656bc4c82902c5546c8dc2a9327775248b902c6d21882e103b0d64f0bc214d42ee9334650daefc3667203d73bc6b38b9b17148ca795c8f787ea5cb7e

test:
  secret_key_base: 6bafe37cee5361871380ec0219e062430df9203d7b3ba87b775f285a768184acd0303b5dfde083b1d6565c42b608340d46ccd308258cc54c6ce215fdc9ad4377

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
